# kustomize_base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- pvc.yaml
- worker.pod.yaml
- php-config.yaml


namespace: ${NAMESPACE_NAME}
nameSuffix: "-${POD_SUFFIX}"

patches:
- target:
    kind: Pod
    name: worker
  patch: |-
    - op: replace
      path: /spec/containers/0/command
      value:
      - /bin/bash
    - op: replace
      path: /spec/containers/0/args
      value:
      - -c
      - /usr/local/bin/entrypoint.sh
