# kustomize_base/php-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: php-config
data:
  php_command.ini: |
    display_errors = On
    log_errors = On
    error_reporting = E_ALL
    max_execution_time = 300
    memory_limit = 512M
    upload_max_filesize = 100M
    post_max_size = 100M
  php.fpf: |
    [global]
    error_log = /proc/self/fd/2 ; Redirect FPM errors to stderr (container logs)
    daemonize = no ; Do not daemonize, let Kubernetes manage process
    
    [www]
    listen = 9000 ; Or the port your FPM process listens on
    pm = dynamic
    pm.max_children = 5
    pm.start_servers = 2
    pm.min_servers = 1
    pm.max_spare_servers = 3
    access.log = /proc/self/fd/2 ; Redirect FPM access logs to stderr
    ; Clear environment variables in FPM workers (common for security)
    clear_env = no
