apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-shared
  namespace: ${NAMESPACE_NAME}
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: nutanix-dynfiles
  volumeMode: Filesystem
